apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "77.6.0"
  install:
    crds: CreateReplace
  values:
    grafana:
      adminPassword: "ChangeThisGrafanaPass!"
      service:
        type: LoadBalancer
